### ISSUE TITLE
Disseny

### ISSUE THREAD

**Issue by quimdt** [slugCoders/metronome#1]
Hola gent,

He creat aquest issue, per fer un seguiment del disseny. 

Si heu vist el mail que us vaig enviar. N'hi havia una de proposat!

Em vaig basar en un aspecte, que consider-ho important, donar-li un toc distintiu de la resta de metronomes, per tal de destacar i que no sigui un més.

A partir d'aquí vaig pensar diferents possibilitats. Entre elles, que la part visual havia de sobresortir de la resta. Hi ha moltes paranoies que es poden fer a la prat gràfica, jugar amb llums, colors, objectes, dibuixos, animacions, etc. Paranoies varies que consider-ho que són gracioses però no útils. Per això em vaig decanta per quelcom més "professional", un pentagrama o pentagrama per a ritmes (no sé com es diu). No sé si existeix alguna llibreria que en permeti fer-ho, perquè totes les que he trobat eren massa complertes, no només eren l'aspecte visual si no també el sonor. 
La idea és que amb només el pentagrama, es pugui fer la majoria de coses. 
       - Canviar les notes (No cal que fem les 8 notes. Això no és un guitar pro!!) podem fer que hi hagi dues o tres notes diferents (diferents accentuacions).  
       - Canvia figures
       - Volum
       - Tap
       - Tempo
       - Compàs
I el que ens pugui passar pel cap.
També que, ja he dit varis cops, es pugui tenir un control de l'aplicació des del teclat, de tal manera que si estàs assajant només amb una tecla poder parar i activar el teclat, pujar/baixar el volum, pujar/baixar el tempo, etc!

I finalment dos punts més.
Per tal de que el gràfic guanyés protagonisme, havia pensat, ocultar els controls gràfics, i que es puguin, desplegar per tal de tenir una visió general de com està la configuració.

I per últim.
Cal fer un menú?
Crec que seria interessant tenir algun apartat on expliqués el típic, qui som?, que és?, com funciona?, com està fet?, perquè?, quan?  Si cal un menú ja és una altre cosa...   

M'agradaria, que diguéssiu la vostre. I que entre tots podem definir cada punt, ben definit! Així tots tenim clar cap a on hem de tirar i podem començar a treballar amb la view i anat col·locant els diferents elements sense necessitat de tenir els gràfics bons.

Ànims i Salut!

Xims.

PD:Aquí podem crear tants issues com vulguem per parlar de temes específics. Hi ha diferents, coses que es poden fer, labels, etc! Us recomano que l'hi feu un cop d'ull això dels issues. Així també tenim fàcil accés a la info que hem discutit i no anar buscant per el gmail, "aquell comentari que havia dit el fulanito quan....".

**Comment by ljoglar** [comment]
Hola family!

Per pintar les notes podem utilitzar aquesta fantástica API. http://www.vexflow.com/

A veure que us sembla!

**Comment by quimdt** [comment]
Merci Luis té bona pinta, acabem de donar-li un parell de voltes a veure que ens pot oferir. 

Però m'agradaria que debatéssim sobre el disseny de l'aplicació.
Que no us agrada, que us agrada, que canviaríeu, etc.

Que això ha de ser un treball conjunt. No costa res dir la vostre.

**Comment by ljoglar** [comment]
Afegeixo aqui la proposta a discutir del chimo.
![metronome](https://cloud.githubusercontent.com/assets/1093310/7955626/b6df534a-09d1-11e5-94b5-09e7484db443.png)

**Comment by ljoglar** [comment]
A mi el tó professional de la proposta m'agrada.
Jo durant els pròxims dies intentaré fer una proposta basada en això però ja fet en html i css. I crec que a partir d'aquesta podrem anar afinant detalls.
Crec que podriem donar un parell de voltes a la visualització del tempo en "play". Es a dir, crec que les notes estan molt bé, perquè a més es instructiu. Però també pot ser que amb alguns ritmes complexos lii. Jo afegiria uns punts que marquin el beat del compas. Enlloc del single point que dibuixa el chimo, jo posaria els punts corresponents al compas (en el cas d'exemple 4) i que es vagin iluminant a la vegada que les notes. (per adaptar-ho a daltinocs, a mes d'iluminació, es podrien fer una mica mes grans).

**Comment by quimdt** [comment]
Em sembla bé d'afegir tots els punts. En el cas de 4/4 amb negres està clar. Però si la figura rítmica canvia no creus que serà més liat? potser estaria bé posar tants punts com notes o q?

**Comment by ljoglar** [comment]
No, jo posaria només els punts del beat. I separaria les notes proporcionalment (Es a dir a sota una blanca hi hauria un punt, despres hi hauria un altre punt sense cap nota damunt i despres la seguent nota tindria l'altre punt a sota). Així es dona la informació de quines figures ritmiques hi ha a cada beat.

**Comment by quimdt** [comment]
Em sembla bé!

**Comment by ljoglar** [comment]
:)

**Comment by MarcRibera** [comment]
Em semblen molt bones propostes.El pentagrama trobo que és molt bona idea, i m'agrada. El tema "crític" crec que està en com integrar pentagrama i boletes no? 

Jo crec que posar aquestes dues referències visuals a la vegada, pot ser una mica confús per a l'Usuari, sobretot aquells que no estàn acostumats al Pentagrama i al veure'l segur que s'espanten. jeje

Total,(i crec que ja ho vaig parlar amb el ximo), veig lo del pentagrama com un "extra", el qual podem desenvolupar ja mateix. Ara bé com a view principal, posaría algo més clàssic, sobretot pel tema de no confondre el personal.

**Comment by quimdt** [comment]
Jo opino diferent, que justament, passaria de la view clàssica. I crec que amb un bon tuto, no te perquè ser difícil d'entendre l'app. Però bé són opinions diferents.

**Comment by quimdt** [comment]
Posaríeu menú? o ho feríeu estil bootsrap, tot en vertical?

**Comment by quimdt** [comment]
I el tema controls? q?

**Comment by ljoglar** [comment]
Jo opinio com el Ximo. Posaria el pentagrama de main view. Si els usuaris han d'apendre una mica a utilitzar-ho que n'aprenguin, no? Si no ho entenen es pk els falten coneixements musicals i així els adquireixen. 

El tema menú, com que estem parlant d'una web de moment jo faria un menú discret horitzontal a dalt de tot. (no entenc que vols dir amb estil bootstrap) Jo pensava utilitzar bootstrap com a llibreria gràfica, pero es pot fer com nosaltres volguem amb elements de bootstrap.  Jo faria com he dit un menu simple i sencill horitzontal fixe amb links de navegació que portin a altres parts de la página. Donat que no serà tanta informació ho faria tot a en seccions pero a la home (tot en una página).

El tema controls els faria com proposes en un desplegable. http://getbootstrap.com/javascript/#collapse

**Comment by quimdt** [comment]
Em refereia al que tu dius tot en una pagina. Em sembla bé el menú vertical i discret.
Val doncs:
Aquestes serien una mica les feines de cara a la view.
-Template html (Luís)
- Codificar view acord amb la template. (Luís ens ho podem partir si et sembla bé. Quan tignuis la template feta, ens repartim la feina)
- El merry està amb el control del tap.

Ja anirem veient

**Comment by MarcRibera** [comment]
Ostres, crec que sense voler he tancat la Issue, o algo.. jajaj

Ok, si preferiu fer-ho amb aquesta View, no problemo migo.

Quedem així doncs, jo vaig fen el Tab!

**Comment by ljoglar** [comment]
Ok, jo en quant tingui una mica de temps, dema o demà passat espero faig l'estructura de l'html i us ho passo i treballem a partir d'aquí.

**Comment by quimdt** [comment]
perfect!
